language: node_js
dist: trusty
node_js:
  - "6.10.1"

script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: shs.epfl
  skip_cleanup: true
  acl: public_read
  region: eu-central-1
  upload-dir: dist
  on:
      branch: master
